name: Render a CV

on:
  push:
    branches:
      - master 
  workflow_call: # to make the workflow triggerable from other workflows (release.yaml)

permissions:
  contents: write

jobs:
  rendercv:
    name: RenderCV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install RenderCV
        run: |
          pip install -r requirements.txt
      - name: RenderCV
        run: |
          cv_file=$(find .  -maxdepth 1 -type f -name "cv.yaml" | head -n 1)
          if [ -z "$cv_file" ]; then
            echo "No cv.yaml file found!"
            exit 1
          fi
          rendercv render $cv_file --pdf-path ${cv_file%.yaml}.pdf --html-path ${cv_file%.yaml}.html --png-path ${cv_file%.yaml}.jpg
      - name: Upload rendercv_output as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: RenderCV Output
          path: rendercv_output
      - name: Push the changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          git fetch origin deploy || git checkout --orphan deploy 
          if git show-ref --verify --quiet refs/heads/deploy; then
            git checkout deploy 
          else
            git checkout --orphan deploy 
          fi

          git add cv.*
          git commit -m "update rendered cv"
          git push origin deploy --force
